extends: airbnb-base
env:
  node: true
rules:
  strict: 0
  global-require: 0
  key-spacing:
    - error
    - align: value
  no-multi-spaces:
    - error
    - exceptions:
        VariableDeclarator: true
  import/no-extraneous-dependencies: 0
  no-unused-vars:
    - error
    - argsIgnorePattern: "next"
  no-param-reassign:
    - error
    - props: false
  no-console: 0
